// GET METHODS
# // GET ALL PUBLIC USERS
# GET http://localhost:3000/api/v1/pu/
# Content-Type: application/json

// GET PUBLIC USER WITH ID
GET http://localhost:3000/api/v1/pu/2/
Content-Type: application/json 


// POST METHODS
# // ADD A STUDENT
# POST http://localhost:3000/api/v1/pu/
# Content-Type: application/json

# {
#     "userid": 3,
#     "username": "username3",
#     "email": "user2@email.com",
#     "password": "password789",
#     "token": null
# }

