services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs: