name: ESLint Server Workflow

on: [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Dependencies
        working-directory: ./server
        run: npm install
      - name: Test Code Linting
        working-directory: ./server
        run: npm run lint
      - name: Save Code Linting Report JSON
        working-directory: ./server
        run: npm run lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        if: always()
        uses: ataylorme/eslint-annotate-action@v2
